name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 22.x
      PORT: 3008
      CYPRESS_baseUrl: http://localhost:3008

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build --if-present

      - name: Run Cypress E2E
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:${{ env.PORT }}
          browser: electron
        env:
          PORT: ${{ env.PORT }}

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: |
            cypress/reports/**/*.html
            **/*-report.html
          if-no-files-found: ignore
